// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
)

type Assignment struct {
	ID             int64         `json:"id"`
	DateAssignment sql.NullTime  `json:"dateAssignment"`
	RoleID         sql.NullInt64 `json:"roleId"`
	PersonID       sql.NullInt64 `json:"personId"`
}
