// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
)

type Person struct {
	ID     int64         `json:"id"`
	Name   string        `json:"name"`
	RoleID sql.NullInt64 `json:"roleId"`
}
