// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
)

type PersonRole struct {
	ID       int64         `json:"id"`
	PersonID sql.NullInt64 `json:"personId"`
	RoleID   sql.NullInt64 `json:"roleId"`
	Foreign  interface{}   `json:"foreign"`
}
