// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function Create(arg1:entity.Assignment):Promise<number>;

export function Delete(arg1:number):Promise<number>;

export function FindAll():Promise<Array<entity.Assignment>>;

export function FindByID(arg1:number):Promise<entity.Assignment>;

export function Update(arg1:entity.Assignment):Promise<number>;
