// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['application']['PersonRoleService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['application']['PersonRoleService']['Delete'](arg1);
}

export function FindAll() {
  return window['go']['application']['PersonRoleService']['FindAll']();
}

export function FindByID(arg1) {
  return window['go']['application']['PersonRoleService']['FindByID'](arg1);
}

export function Update(arg1) {
  return window['go']['application']['PersonRoleService']['Update'](arg1);
}
