// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['application']['PersonService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['application']['PersonService']['Delete'](arg1);
}

export function FindAll() {
  return window['go']['application']['PersonService']['FindAll']();
}

export function FindByID(arg1) {
  return window['go']['application']['PersonService']['FindByID'](arg1);
}

export function Update(arg1) {
  return window['go']['application']['PersonService']['Update'](arg1);
}
